// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnnlineStore.Data;

#nullable disable

namespace OnnlineStore.Migrations.OnlineStoreDb
{
    [DbContext(typeof(OnlineStoreDbContext))]
    [Migration("20240815090357_seed some data")]
    partial class seedsomedata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnnlineStore.Models.Domain.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("080b5cb7-b849-40cf-9b90-645cde291033"),
                            Biography = "Mark Twain was an American writer and humorist known for his novels 'The Adventures of Tom Sawyer' and 'Adventures of Huckleberry Finn.",
                            Name = "Mark Twain"
                        },
                        new
                        {
                            Id = new Guid("b893780a-45a1-41a3-9144-161864aca2ba"),
                            Biography = "Jane Austen was an English novelist known for her six major novels including 'Pride and Prejudice' and 'Sense and Sensibility'.",
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = new Guid("83b98008-1cdd-4432-b87e-fc9f7abcaedc"),
                            Biography = "J.K. Rowling is a British author, best known for writing the 'Harry Potter' series which has become one of the best-selling book series in history.",
                            Name = "J.K. Rowling"
                        });
                });

            modelBuilder.Entity("OnnlineStore.Models.Domain.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f5e32e2-b224-4497-9dd8-ab5e0ca5ec8e"),
                            AuthorId = new Guid("080b5cb7-b849-40cf-9b90-645cde291033"),
                            CategoryId = new Guid("88f9ab88-463b-4c13-bf25-e18b6c480f9c"),
                            CoverImageUrl = "tom_sawyer.jpg",
                            Description = "A novel by Mark Twain about a young boy's adventures in the American South.",
                            Price = 19.99m,
                            Title = "The Adventures of Tom Sawyer"
                        },
                        new
                        {
                            Id = new Guid("c5de44d9-ceb9-4481-bdfd-ec47a5d25fb3"),
                            AuthorId = new Guid("b893780a-45a1-41a3-9144-161864aca2ba"),
                            CategoryId = new Guid("88f9ab88-463b-4c13-bf25-e18b6c480f9c"),
                            CoverImageUrl = "pride_and_prejudice.jpg",
                            Description = "A classic novel by Jane Austen exploring themes of love and social class.",
                            Price = 14.99m,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("67375ef5-72d0-4451-ae8f-3f6055edcdd6"),
                            AuthorId = new Guid("83b98008-1cdd-4432-b87e-fc9f7abcaedc"),
                            CategoryId = new Guid("afd1fa53-a0ff-48ef-9704-300ed1837ba4"),
                            CoverImageUrl = "harry_potter.jpg",
                            Description = "The first book in the Harry Potter series by J.K. Rowling.",
                            Price = 24.99m,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = new Guid("2eb18ede-7b1b-4d83-b1e4-871cce818c8a"),
                            AuthorId = new Guid("080b5cb7-b849-40cf-9b90-645cde291033"),
                            CategoryId = new Guid("f57eaa3d-89eb-4cef-bbe0-2aacc290b439"),
                            CoverImageUrl = "7_habits.jpg",
                            Description = "A self-help book by Stephen R. Covey that provides a principle-centered approach for solving personal and professional problems.",
                            Price = 29.99m,
                            Title = "The 7 Habits of Highly Effective People"
                        });
                });

            modelBuilder.Entity("OnnlineStore.Models.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12ab5a40-b795-40ce-b15d-8018422c8577"),
                            Name = "Educational"
                        },
                        new
                        {
                            Id = new Guid("f57eaa3d-89eb-4cef-bbe0-2aacc290b439"),
                            Name = "Self development"
                        },
                        new
                        {
                            Id = new Guid("88f9ab88-463b-4c13-bf25-e18b6c480f9c"),
                            Name = "Novel"
                        },
                        new
                        {
                            Id = new Guid("afd1fa53-a0ff-48ef-9704-300ed1837ba4"),
                            Name = "Children"
                        });
                });

            modelBuilder.Entity("OnnlineStore.Models.Domain.Book", b =>
                {
                    b.HasOne("OnnlineStore.Models.Domain.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnnlineStore.Models.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
